Update dotnet.yml

diff --git a/.github/workflows/dotnet.yml b/.github/workflows/dotnet.yml
--- a/.github/workflows/dotnet.yml
+++ b/.github/workflows/dotnet.yml
@@ -23,4 +23,12 @@ jobs:
     - name: Build
       run: dotnet build --no-restore
     - name: Test
-      run: dotnet test /p:CollectCoverage=true --no-build --verbosity normal
+      run: dotnet test --no-build --verbosity normal --configuration Release --logger "trx;LogFileNam=test-results.trx" || true
+
+    - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: DotNet Tests            # Name of the check run which will be created
+          path: test-results.trx    # Path to test results
+          reporter: dotnet-trx        # Format of test results
